// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a.proto

package com.company.protobuf;

public final class TrackPointbuf {
  private TrackPointbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TrackPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.TrackPoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required sint32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required sint32 x = 1;</code>
     */
    int getX();

    /**
     * <code>required sint32 y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required sint32 y = 2;</code>
     */
    int getY();

    /**
     * <code>required fixed64 ts = 3;</code>
     */
    boolean hasTs();
    /**
     * <code>required fixed64 ts = 3;</code>
     */
    long getTs();

    /**
     * <code>required int32 heading = 4;</code>
     */
    boolean hasHeading();
    /**
     * <code>required int32 heading = 4;</code>
     */
    int getHeading();

    /**
     * <code>required int32 speed = 5;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required int32 speed = 5;</code>
     */
    int getSpeed();

    /**
     * <code>required int32 sat = 6;</code>
     */
    boolean hasSat();
    /**
     * <code>required int32 sat = 6;</code>
     */
    int getSat();

    /**
     * <code>required int32 height = 7;</code>
     */
    boolean hasHeight();
    /**
     * <code>required int32 height = 7;</code>
     */
    int getHeight();

    /**
     * <code>required int32 precsion = 8;</code>
     */
    boolean hasPrecsion();
    /**
     * <code>required int32 precsion = 8;</code>
     */
    int getPrecsion();

    /**
     * <code>required int32 fixmodelArr = 9;</code>
     */
    boolean hasFixmodelArr();
    /**
     * <code>required int32 fixmodelArr = 9;</code>
     */
    int getFixmodelArr();
  }
  /**
   * Protobuf type {@code protobuf.TrackPoint}
   */
  public static final class TrackPoint extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.TrackPoint)
      TrackPointOrBuilder {
    // Use TrackPoint.newBuilder() to construct.
    private TrackPoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TrackPoint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TrackPoint defaultInstance;
    public static TrackPoint getDefaultInstance() {
      return defaultInstance;
    }

    public TrackPoint getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TrackPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readSInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              ts_ = input.readFixed64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              heading_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              speed_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sat_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              height_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              precsion_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              fixmodelArr_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.company.protobuf.TrackPointbuf.internal_static_protobuf_TrackPoint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.company.protobuf.TrackPointbuf.internal_static_protobuf_TrackPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.company.protobuf.TrackPointbuf.TrackPoint.class, com.company.protobuf.TrackPointbuf.TrackPoint.Builder.class);
    }

    public static com.google.protobuf.Parser<TrackPoint> PARSER =
        new com.google.protobuf.AbstractParser<TrackPoint>() {
      public TrackPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrackPoint(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TrackPoint> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required sint32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>required sint32 y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required sint32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int TS_FIELD_NUMBER = 3;
    private long ts_;
    /**
     * <code>required fixed64 ts = 3;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required fixed64 ts = 3;</code>
     */
    public long getTs() {
      return ts_;
    }

    public static final int HEADING_FIELD_NUMBER = 4;
    private int heading_;
    /**
     * <code>required int32 heading = 4;</code>
     */
    public boolean hasHeading() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 heading = 4;</code>
     */
    public int getHeading() {
      return heading_;
    }

    public static final int SPEED_FIELD_NUMBER = 5;
    private int speed_;
    /**
     * <code>required int32 speed = 5;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 speed = 5;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    public static final int SAT_FIELD_NUMBER = 6;
    private int sat_;
    /**
     * <code>required int32 sat = 6;</code>
     */
    public boolean hasSat() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 sat = 6;</code>
     */
    public int getSat() {
      return sat_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 7;
    private int height_;
    /**
     * <code>required int32 height = 7;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 height = 7;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int PRECSION_FIELD_NUMBER = 8;
    private int precsion_;
    /**
     * <code>required int32 precsion = 8;</code>
     */
    public boolean hasPrecsion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 precsion = 8;</code>
     */
    public int getPrecsion() {
      return precsion_;
    }

    public static final int FIXMODELARR_FIELD_NUMBER = 9;
    private int fixmodelArr_;
    /**
     * <code>required int32 fixmodelArr = 9;</code>
     */
    public boolean hasFixmodelArr() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 fixmodelArr = 9;</code>
     */
    public int getFixmodelArr() {
      return fixmodelArr_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
      ts_ = 0L;
      heading_ = 0;
      speed_ = 0;
      sat_ = 0;
      height_ = 0;
      precsion_ = 0;
      fixmodelArr_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeading()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrecsion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFixmodelArr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed64(3, ts_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, heading_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, sat_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, height_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, precsion_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, fixmodelArr_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, ts_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, heading_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, sat_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, height_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, precsion_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, fixmodelArr_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.company.protobuf.TrackPointbuf.TrackPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.company.protobuf.TrackPointbuf.TrackPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.company.protobuf.TrackPointbuf.TrackPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.TrackPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.TrackPoint)
        com.company.protobuf.TrackPointbuf.TrackPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.company.protobuf.TrackPointbuf.internal_static_protobuf_TrackPoint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.company.protobuf.TrackPointbuf.internal_static_protobuf_TrackPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.company.protobuf.TrackPointbuf.TrackPoint.class, com.company.protobuf.TrackPointbuf.TrackPoint.Builder.class);
      }

      // Construct using com.company.protobuf.TrackPointbuf.TrackPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        heading_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        sat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        precsion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        fixmodelArr_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.company.protobuf.TrackPointbuf.internal_static_protobuf_TrackPoint_descriptor;
      }

      public com.company.protobuf.TrackPointbuf.TrackPoint getDefaultInstanceForType() {
        return com.company.protobuf.TrackPointbuf.TrackPoint.getDefaultInstance();
      }

      public com.company.protobuf.TrackPointbuf.TrackPoint build() {
        com.company.protobuf.TrackPointbuf.TrackPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.company.protobuf.TrackPointbuf.TrackPoint buildPartial() {
        com.company.protobuf.TrackPointbuf.TrackPoint result = new com.company.protobuf.TrackPointbuf.TrackPoint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.heading_ = heading_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sat_ = sat_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.precsion_ = precsion_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.fixmodelArr_ = fixmodelArr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.company.protobuf.TrackPointbuf.TrackPoint) {
          return mergeFrom((com.company.protobuf.TrackPointbuf.TrackPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.company.protobuf.TrackPointbuf.TrackPoint other) {
        if (other == com.company.protobuf.TrackPointbuf.TrackPoint.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasHeading()) {
          setHeading(other.getHeading());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasSat()) {
          setSat(other.getSat());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasPrecsion()) {
          setPrecsion(other.getPrecsion());
        }
        if (other.hasFixmodelArr()) {
          setFixmodelArr(other.getFixmodelArr());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasTs()) {
          
          return false;
        }
        if (!hasHeading()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        if (!hasSat()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasPrecsion()) {
          
          return false;
        }
        if (!hasFixmodelArr()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.company.protobuf.TrackPointbuf.TrackPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.company.protobuf.TrackPointbuf.TrackPoint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>required sint32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required sint32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>required sint32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required sint32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required sint32 y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <code>required fixed64 ts = 3;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required fixed64 ts = 3;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>required fixed64 ts = 3;</code>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000004;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 ts = 3;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ts_ = 0L;
        onChanged();
        return this;
      }

      private int heading_ ;
      /**
       * <code>required int32 heading = 4;</code>
       */
      public boolean hasHeading() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 heading = 4;</code>
       */
      public int getHeading() {
        return heading_;
      }
      /**
       * <code>required int32 heading = 4;</code>
       */
      public Builder setHeading(int value) {
        bitField0_ |= 0x00000008;
        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 heading = 4;</code>
       */
      public Builder clearHeading() {
        bitField0_ = (bitField0_ & ~0x00000008);
        heading_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>required int32 speed = 5;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 speed = 5;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>required int32 speed = 5;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000010;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 speed = 5;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        speed_ = 0;
        onChanged();
        return this;
      }

      private int sat_ ;
      /**
       * <code>required int32 sat = 6;</code>
       */
      public boolean hasSat() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 sat = 6;</code>
       */
      public int getSat() {
        return sat_;
      }
      /**
       * <code>required int32 sat = 6;</code>
       */
      public Builder setSat(int value) {
        bitField0_ |= 0x00000020;
        sat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sat = 6;</code>
       */
      public Builder clearSat() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sat_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>required int32 height = 7;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 height = 7;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>required int32 height = 7;</code>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000040;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 height = 7;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000040);
        height_ = 0;
        onChanged();
        return this;
      }

      private int precsion_ ;
      /**
       * <code>required int32 precsion = 8;</code>
       */
      public boolean hasPrecsion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 precsion = 8;</code>
       */
      public int getPrecsion() {
        return precsion_;
      }
      /**
       * <code>required int32 precsion = 8;</code>
       */
      public Builder setPrecsion(int value) {
        bitField0_ |= 0x00000080;
        precsion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 precsion = 8;</code>
       */
      public Builder clearPrecsion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        precsion_ = 0;
        onChanged();
        return this;
      }

      private int fixmodelArr_ ;
      /**
       * <code>required int32 fixmodelArr = 9;</code>
       */
      public boolean hasFixmodelArr() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 fixmodelArr = 9;</code>
       */
      public int getFixmodelArr() {
        return fixmodelArr_;
      }
      /**
       * <code>required int32 fixmodelArr = 9;</code>
       */
      public Builder setFixmodelArr(int value) {
        bitField0_ |= 0x00000100;
        fixmodelArr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 fixmodelArr = 9;</code>
       */
      public Builder clearFixmodelArr() {
        bitField0_ = (bitField0_ & ~0x00000100);
        fixmodelArr_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.TrackPoint)
    }

    static {
      defaultInstance = new TrackPoint(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.TrackPoint)
  }

  public interface RoadProbeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.RoadProbe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>required string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>required .protobuf.TrackPoint tracks = 2;</code>
     */
    boolean hasTracks();
    /**
     * <code>required .protobuf.TrackPoint tracks = 2;</code>
     */
    com.company.protobuf.TrackPointbuf.TrackPoint getTracks();
    /**
     * <code>required .protobuf.TrackPoint tracks = 2;</code>
     */
    com.company.protobuf.TrackPointbuf.TrackPointOrBuilder getTracksOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.RoadProbe}
   */
  public static final class RoadProbe extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.RoadProbe)
      RoadProbeOrBuilder {
    // Use RoadProbe.newBuilder() to construct.
    private RoadProbe(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoadProbe(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoadProbe defaultInstance;
    public static RoadProbe getDefaultInstance() {
      return defaultInstance;
    }

    public RoadProbe getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoadProbe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uid_ = bs;
              break;
            }
            case 18: {
              com.company.protobuf.TrackPointbuf.TrackPoint.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = tracks_.toBuilder();
              }
              tracks_ = input.readMessage(com.company.protobuf.TrackPointbuf.TrackPoint.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tracks_);
                tracks_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.company.protobuf.TrackPointbuf.internal_static_protobuf_RoadProbe_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.company.protobuf.TrackPointbuf.internal_static_protobuf_RoadProbe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.company.protobuf.TrackPointbuf.RoadProbe.class, com.company.protobuf.TrackPointbuf.RoadProbe.Builder.class);
    }

    public static com.google.protobuf.Parser<RoadProbe> PARSER =
        new com.google.protobuf.AbstractParser<RoadProbe>() {
      public RoadProbe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoadProbe(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoadProbe> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private java.lang.Object uid_;
    /**
     * <code>required string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACKS_FIELD_NUMBER = 2;
    private com.company.protobuf.TrackPointbuf.TrackPoint tracks_;
    /**
     * <code>required .protobuf.TrackPoint tracks = 2;</code>
     */
    public boolean hasTracks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protobuf.TrackPoint tracks = 2;</code>
     */
    public com.company.protobuf.TrackPointbuf.TrackPoint getTracks() {
      return tracks_;
    }
    /**
     * <code>required .protobuf.TrackPoint tracks = 2;</code>
     */
    public com.company.protobuf.TrackPointbuf.TrackPointOrBuilder getTracksOrBuilder() {
      return tracks_;
    }

    private void initFields() {
      uid_ = "";
      tracks_ = com.company.protobuf.TrackPointbuf.TrackPoint.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTracks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTracks().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, tracks_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tracks_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.company.protobuf.TrackPointbuf.RoadProbe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.company.protobuf.TrackPointbuf.RoadProbe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.company.protobuf.TrackPointbuf.RoadProbe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.RoadProbe}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.RoadProbe)
        com.company.protobuf.TrackPointbuf.RoadProbeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.company.protobuf.TrackPointbuf.internal_static_protobuf_RoadProbe_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.company.protobuf.TrackPointbuf.internal_static_protobuf_RoadProbe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.company.protobuf.TrackPointbuf.RoadProbe.class, com.company.protobuf.TrackPointbuf.RoadProbe.Builder.class);
      }

      // Construct using com.company.protobuf.TrackPointbuf.RoadProbe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTracksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (tracksBuilder_ == null) {
          tracks_ = com.company.protobuf.TrackPointbuf.TrackPoint.getDefaultInstance();
        } else {
          tracksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.company.protobuf.TrackPointbuf.internal_static_protobuf_RoadProbe_descriptor;
      }

      public com.company.protobuf.TrackPointbuf.RoadProbe getDefaultInstanceForType() {
        return com.company.protobuf.TrackPointbuf.RoadProbe.getDefaultInstance();
      }

      public com.company.protobuf.TrackPointbuf.RoadProbe build() {
        com.company.protobuf.TrackPointbuf.RoadProbe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.company.protobuf.TrackPointbuf.RoadProbe buildPartial() {
        com.company.protobuf.TrackPointbuf.RoadProbe result = new com.company.protobuf.TrackPointbuf.RoadProbe(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (tracksBuilder_ == null) {
          result.tracks_ = tracks_;
        } else {
          result.tracks_ = tracksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.company.protobuf.TrackPointbuf.RoadProbe) {
          return mergeFrom((com.company.protobuf.TrackPointbuf.RoadProbe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.company.protobuf.TrackPointbuf.RoadProbe other) {
        if (other == com.company.protobuf.TrackPointbuf.RoadProbe.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasTracks()) {
          mergeTracks(other.getTracks());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasTracks()) {
          
          return false;
        }
        if (!getTracks().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.company.protobuf.TrackPointbuf.RoadProbe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.company.protobuf.TrackPointbuf.RoadProbe) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <code>required string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }

      private com.company.protobuf.TrackPointbuf.TrackPoint tracks_ = com.company.protobuf.TrackPointbuf.TrackPoint.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.company.protobuf.TrackPointbuf.TrackPoint, com.company.protobuf.TrackPointbuf.TrackPoint.Builder, com.company.protobuf.TrackPointbuf.TrackPointOrBuilder> tracksBuilder_;
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      public boolean hasTracks() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      public com.company.protobuf.TrackPointbuf.TrackPoint getTracks() {
        if (tracksBuilder_ == null) {
          return tracks_;
        } else {
          return tracksBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      public Builder setTracks(com.company.protobuf.TrackPointbuf.TrackPoint value) {
        if (tracksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tracks_ = value;
          onChanged();
        } else {
          tracksBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      public Builder setTracks(
          com.company.protobuf.TrackPointbuf.TrackPoint.Builder builderForValue) {
        if (tracksBuilder_ == null) {
          tracks_ = builderForValue.build();
          onChanged();
        } else {
          tracksBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      public Builder mergeTracks(com.company.protobuf.TrackPointbuf.TrackPoint value) {
        if (tracksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              tracks_ != com.company.protobuf.TrackPointbuf.TrackPoint.getDefaultInstance()) {
            tracks_ =
              com.company.protobuf.TrackPointbuf.TrackPoint.newBuilder(tracks_).mergeFrom(value).buildPartial();
          } else {
            tracks_ = value;
          }
          onChanged();
        } else {
          tracksBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      public Builder clearTracks() {
        if (tracksBuilder_ == null) {
          tracks_ = com.company.protobuf.TrackPointbuf.TrackPoint.getDefaultInstance();
          onChanged();
        } else {
          tracksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      public com.company.protobuf.TrackPointbuf.TrackPoint.Builder getTracksBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTracksFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      public com.company.protobuf.TrackPointbuf.TrackPointOrBuilder getTracksOrBuilder() {
        if (tracksBuilder_ != null) {
          return tracksBuilder_.getMessageOrBuilder();
        } else {
          return tracks_;
        }
      }
      /**
       * <code>required .protobuf.TrackPoint tracks = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.company.protobuf.TrackPointbuf.TrackPoint, com.company.protobuf.TrackPointbuf.TrackPoint.Builder, com.company.protobuf.TrackPointbuf.TrackPointOrBuilder> 
          getTracksFieldBuilder() {
        if (tracksBuilder_ == null) {
          tracksBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.company.protobuf.TrackPointbuf.TrackPoint, com.company.protobuf.TrackPointbuf.TrackPoint.Builder, com.company.protobuf.TrackPointbuf.TrackPointOrBuilder>(
                  getTracks(),
                  getParentForChildren(),
                  isClean());
          tracks_ = null;
        }
        return tracksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.RoadProbe)
    }

    static {
      defaultInstance = new RoadProbe(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.RoadProbe)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_TrackPoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_TrackPoint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_RoadProbe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_RoadProbe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007a.proto\022\010protobuf\"\222\001\n\nTrackPoint\022\t\n\001x\030" +
      "\001 \002(\021\022\t\n\001y\030\002 \002(\021\022\n\n\002ts\030\003 \002(\006\022\017\n\007heading\030" +
      "\004 \002(\005\022\r\n\005speed\030\005 \002(\005\022\013\n\003sat\030\006 \002(\005\022\016\n\006hei" +
      "ght\030\007 \002(\005\022\020\n\010precsion\030\010 \002(\005\022\023\n\013fixmodelA" +
      "rr\030\t \002(\005\">\n\tRoadProbe\022\013\n\003uid\030\001 \002(\t\022$\n\006tr" +
      "acks\030\002 \002(\0132\024.protobuf.TrackPointB%\n\024com." +
      "company.protobufB\rTrackPointbuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_TrackPoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_TrackPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_TrackPoint_descriptor,
        new java.lang.String[] { "X", "Y", "Ts", "Heading", "Speed", "Sat", "Height", "Precsion", "FixmodelArr", });
    internal_static_protobuf_RoadProbe_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_RoadProbe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_RoadProbe_descriptor,
        new java.lang.String[] { "Uid", "Tracks", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
